# Configure and deploy the web servers. Note that we include two roles here,
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: {{windows_webservers}}
  connection: winrm

  vars:
    ansible_ssh_port : 5986

  roles:
  - iis
  - web

  tags:
  - web
